import { apiPlugin, storyblokInit } from "@storyblok/react/rsc";
import { inter, roboto_mono } from './fonts';
import StoryblokBridgeLoader from "@storyblok/react/bridge-loader";
import './global.css';
import { StoryblokProvider } from '@deardigital/shop/ui';

export const metadata = {
  title: 'Welcome to shop',
  description: 'Generated by create-nx-workspace',
};

storyblokInit({
  accessToken: process.env.NEXT_PUBLIC_STORYBLOK_API_TOKEN,
  use: [apiPlugin],
  apiOptions: {
    cache: {
      clear: "auto",
      type: "memory",
    },
  },
});

export default function RootLayout({ children }: {
  children: React.ReactNode;
}) {
  return (
    <StoryblokProvider>
      <html lang="en" className={`${inter.variable} ${roboto_mono.variable}`}>
        <body>{children}</body>
        <StoryblokBridgeLoader options={{}} />
      </html>
    </StoryblokProvider>
  );
}
