name: CI

on:
  push:
    branches: [ feature/* ]

jobs:
  build-develop:
    runs-on: ubuntu-latest
    name: Build develop
    steps:
      - uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - run: |
          npm ci
          npx nx format:check
          npx nx affected -t lint --parallel=3
          npx nx affected -t build --parallel=3
